Type: AWS::EC2::VPC

Properties:

  CidrBlock: 10.101.0.0/16

  EnableDnsSupport: true

  EnableDnsHostnames: true

  Type: AWS::EC2::Subnet

Properties:

  VpcId: !Ref VPC

  CidrBlock: 10.101.0.0/24

  AvailabilityZone: us-east-1a

  Type: AWS::EC2::Subnet

Properties:

  VpcId: !Ref VPC

  CidrBlock: 10.101.0.0/24

  AvailabilityZone: us-east-1a